# Generated by Django 2.1.7 on 2019-12-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_gen', '0003_auto_20191214_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prescription_gen.PrescriptionMedicine'),
            preserve_default=False,
        ),
    ]
